[package]
name = "reps"
version = "0.1.0"
authors = ["Simon M. <git@simon.marache.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "3.2.15"
termion = "1.5.5"